version: "3.9"
services:
  cctv:
    build: .
    container_name: cctv_inteligente
    restart: unless-stopped
    volumes:
      - ./recordings:/app/recordings
      - ./evidencias:/app/evidencias
      - ./reports:/app/reports
      - ./config_history:/app/config_history
      - ./faces:/app/faces
      - ./people.db:/app/people.db
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Mexico_City